/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-Jan-2017 00:39:50 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS Childrelation CASCADE
;

/* Create Tables */

CREATE TABLE Childrelation
(
	uuid varchar(36) NULL,
	history varchar(36) NULL,
	guid bigserial NOT NULL,
	LIST bytea NULL,
	SUBTYPE varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Childrelation ADD CONSTRAINT PK_Childrelation
	PRIMARY KEY (guid)
;

CREATE INDEX Childrelation_history_idx ON Childrelation (history ASC)
;

CREATE INDEX Childrelation_uuid_idx ON Childrelation (uuid ASC)
;

/* Create Table Comments, Sequences for Autonumber Columns */

 